import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import { useEffect, useState } from "react";
import { FlexContainer, Typography } from "@/components/shared/components";
import StrategyPage from "@/components/strategy";
import { SupportedChainIds } from "@/types";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const Home: NextPage = () => {
  const [isClient, setIsClient] = useState(false);

  const { address, chainId } = useAccount();

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) {
    return <Typography type="BODY_MEDIUM_S">Loading...</Typography>;
  }

  if (!address || !chainId) {
    return <ConnectButton />;
  }

  return (
    <FlexContainer
      style={{
        height: "100vh",
      }}
      width={100}
    >
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <StrategyPage eoa={address} chainId={chainId as SupportedChainIds} />
    </FlexContainer>
  );
};

export default Home;
